# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 홈
    url: /
    weight: 10
  - name: 이력서
    url: about/
    weight: 20
  - name: 자바
    weight: 30
    children:
      - name: 스터디
        url: about/
        weight: 31
      - name: 프로젝트
        url: about/
        weight: 32
  - name: C++
    url: about/
    weight: 40
  - name: 알고리즘
    url: about/
    weight: 50
    children:
      - name: 탐색
        url: about/
        weight: 51
      - name: 정렬
        url: about/
        weight: 52
      - name: 최단거리
        url: about/
        weight: 53
  - name: 기타
    url: about/
    weight: 60
  - name: 취미들
    url: about/
    weight: 70
    children:
      - name: 노래
        url: about/
        weight: 71
      - name: 칵테일
        url: about/
        weight: 72
